### ISSUE TITLE
Controller Login return 400 

### ISSUE THREAD

**Issue by guillaumecb34** [PivotStick/gatos#1]
Resolve !!

Path : "gatos/crypto.js"

Method : compare

(Before)

<img width="543" alt="Capture d’écran 2022-06-02 à 10 28 35" src="https://user-images.githubusercontent.com/57677425/171588928-e360e0ad-1eba-4407-8957-fc9f36bdc2e2.png">

(After)

<img width="528" alt="Capture d’écran 2022-06-02 à 10 33 13" src="https://user-images.githubusercontent.com/57677425/171589414-013c5ab7-a01a-4d86-82f9-1dfd23b14638.png">

**Comment by PivotStick** [comment]
Merci c'est déjà fix !
